<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_ingresos extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'ticket' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'estado_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'tipo_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'fingreso' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
			'motivo' => array(
				'type' => 'VARCHAR',
				'constraint' => 200,
			),
			'descripcion' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'fsalida' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
			'diagnostico' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'ubicacion_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('ingresos', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('ingresos');
	}
}