<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_migrations extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'version' => array(
				'type' => 'INT',
				'constraint' => 3,
			),
		));

		$this->dbforge->create_table('migrations', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('migrations');
	}
}