<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_usuarios extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 5,
			),
			'nombre' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'apellido' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'email' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'password' => array(
				'type' => 'VARCHAR',
				'constraint' => 40,
			),
			'date_created' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('usuarios', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('usuarios');
	}
}