<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Ingresos extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
                self::$relationships = array (
                        'tipos' => ORM::belongs_to('\\Model\\Tipos'),
                        'estados' => ORM::belongs_to('\\Model\\Estados'),
                        'ubicaciones' => ORM::belongs_to('\\Model\\Ubicaciones')
                    
                );
            
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'ticket' => ORM::field('int[11]',array('required','max_length[11]')),
			'asset' => ORM::field('int[7]', array('required','max_length[7]')),
			'estado_id' => ORM::field('int[11]',array('required')),
			'tipo_id' => ORM::field('int[11]',array('required')),
			'fingreso' => ORM::field('datetime',array('required')),
			'motivo' => ORM::field('char[200]',array('required','max_length[200]')),
			'descripcion' => ORM::field('string',array('required','max_length[200]')),
			'fsalida' => ORM::field('datetime'),
			'diagnostico' => ORM::field('string'),
			'ubicacion_id' => ORM::field('int[11]'),
		);

	}
}
