<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Ubicaciones extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
                
                self::$relationships = array (
                        'ingresos' => ORM::has_many('\\Model\\Ingresos')
                );
                
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'ubicacion' => ORM::field('char[45]'),
		);

	}
}
