<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Usuarios extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[5]'),
			'nombre' => ORM::field('char[40]'),
			'apellido' => ORM::field('char[40]'),
			'email' => ORM::field('char[128]'),
			'password' => ORM::field('char[40]'),
            'app' => ORM::field('char[40]'),
            'userRole' => ORM::field('char[40]'),
			'date_created' => ORM::field('datetime'),
		);

	}
}